### PR TITLE
Buffering state listener

### PR DESCRIPTION
**Pull request by Rakesh777**
Added delegate method to listen buffering states. This can be useful to
show processing when buffer is empty and hide process indicator when buffer is ready to
play.

### CODE REVIEW

**Comment by piemonte** [comment]
hey @Rakesh777 thanks much, nice changes. i have a couple minor requests to your change so that i can merge it in, if you don't mind.

- the new delegate method is optional, can we protect clients that don't implement this method by checking if "respondsToSelector" before making those calls? could cause a crash
- could the Xcode shared metadata, be dropped from the checkin?

**Comment by Rakesh777** [comment]
@piemonte. First of all, thanks for such a great library. I am using it in one of my ongoing projects.

And yes, with all my pleasure I will do necessary changes... And sorry for Xcode shared metadata... This was my first ever commit on github.. ;)

**Comment by piemonte** [comment]
hey, no big deal. congrats on the first contribution, that's awesome. :v:

looks good :boom: :boom: :boom:

**Comment by Rakesh777** [comment]
Hey, thank you so much. U made me feel proud and confident.. Cheers to your efforts and such a beautiful library. Will look forward to give it more time whenever possible.

**Pull request merged**
